definitions:
  types.CreateListPayload:
    properties:
      title:
        type: string
    required:
    - title
    type: object
  types.CreateProjectPayload:
    properties:
      status:
        enum:
        - not started
        - in progress
        - completed
        type: string
      title:
        type: string
    required:
    - status
    - title
    type: object
  types.CreateTaskPayload:
    properties:
      title:
        type: string
    required:
    - title
    type: object
  types.UpdateListPayload:
    properties:
      title:
        type: string
    required:
    - title
    type: object
  types.UpdateProjectPayload:
    properties:
      status:
        enum:
        - not started
        - in progress
        - completed
        type: string
      title:
        type: string
    required:
    - status
    - title
    type: object
  types.UpdateTaskPayload:
    properties:
      done:
        type: boolean
      title:
        type: string
    required:
    - title
    type: object
info:
  contact: {}
paths:
  /api/v1/lists:
    get:
      description: Get all lists
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get all lists
      tags:
      - lists
    post:
      consumes:
      - application/json
      description: Create a new list
      parameters:
      - description: Create List Payload
        in: body
        name: list
        required: true
        schema:
          $ref: '#/definitions/types.CreateListPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Create a new list
      tags:
      - lists
  /api/v1/lists/{id}:
    delete:
      description: Delete a list
      parameters:
      - description: List ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Delete a list
      tags:
      - lists
    put:
      consumes:
      - application/json
      description: Update a list
      parameters:
      - description: List ID
        in: path
        name: id
        required: true
        type: string
      - description: Update List Payload
        in: body
        name: list
        required: true
        schema:
          $ref: '#/definitions/types.UpdateListPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Update a list
      tags:
      - lists
  /api/v1/lists/{listID}/tasks:
    get:
      description: Get all tasks for a list
      parameters:
      - description: List ID
        in: path
        name: listID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get all tasks for a list
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: Create a new task for a list
      parameters:
      - description: List ID
        in: path
        name: listID
        required: true
        type: string
      - description: Create Task Payload
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/types.CreateTaskPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Create a new task for a list
      tags:
      - tasks
  /api/v1/lists/{listID}/tasks/{taskID}:
    delete:
      description: Delete a task
      parameters:
      - description: Task ID
        in: path
        name: taskID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Delete a task
      tags:
      - tasks
    put:
      consumes:
      - application/json
      description: Update a task
      parameters:
      - description: Task ID
        in: path
        name: taskID
        required: true
        type: string
      - description: Update Task Payload
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/types.UpdateTaskPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Update a task
      tags:
      - tasks
  /api/v1/lists/{listID}/tasks/{taskID}/done:
    patch:
      consumes:
      - application/json
      description: Mark a task as done
      parameters:
      - description: Task ID
        in: path
        name: taskID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Mark a task as done
      tags:
      - tasks
  /api/v1/lists/{listID}/tasks/{taskID}/undone:
    patch:
      consumes:
      - application/json
      description: Mark a task as undone
      parameters:
      - description: Task ID
        in: path
        name: taskID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Mark a task as undone
      tags:
      - tasks
  /api/v1/projects:
    get:
      description: Get all projects
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get all projects
      tags:
      - projects
    post:
      consumes:
      - application/json
      description: Create a new project
      parameters:
      - description: Create Project Payload
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/types.CreateProjectPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Create a new project
      tags:
      - projects
  /api/v1/projects/{id}:
    delete:
      description: Delete a project
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Delete a project
      tags:
      - projects
    put:
      consumes:
      - application/json
      description: Update a project
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Project Payload
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/types.UpdateProjectPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Update a project
      tags:
      - projects
swagger: "2.0"
